### PR TITLE
Changes settings to solve cryptic runtime error

### PR DESCRIPTION
**Pull request by valeriyvan**
Changes settings to solve cryptic runtime error "dyld: Library not loaded: @rpath/GPUImage.framework/GPUImage".

### CODE REVIEW

**Comment by mikaelhellqvist** [comment]
I still get that error message. This is the first time trying to launch this project so I might have missed something.

**Comment by garnele007** [comment]
@mikaelhellqvist Could not reproduce. Did you try to clean your project? If you still get the error could please you send me your project file (for debugging)?

**Comment by mikaelhellqvist** [comment]
@garnele007 I'm just trying to run the example project - Swift OCR Camera. Have I missed a step?

**Comment by garnele007** [comment]
@mikaelhellqvist Strange. Does it work, if you first build the Swift OCR framework and after that the app? I really don't know why it isn't working for you.

**Comment by mikaelhellqvist** [comment]
@garnele007 my testing device has 9.3.2. Maybe that could be the cause? It launches on the simulator.

**Comment by garnele007** [comment]
@mikaelhellqvist I'm sorry but I have no idea why it isn't working. 9.3.2 shouldn't be a problem. I have to look into it later today.

**Comment by mikaelhellqvist** [comment]
@garnele007 No problem. Thanks for looking into it!

**Comment by garnele007** [comment]
@mikaelhellqvist I fixed it by adding the GPUImage framework to the Embedded Binaries.

**Pull request merged**
